---
# handlers file for postgres
- name: restart postgres
  service: name=postgresql state=restarted
  become: True

- name: load database
  command: psql -h localhost -d {{ database_name }} -U {{ database_user }} -f /tmp/{{ database_dump.files[0] }}
