---
# tasks file for postgres
- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - libpq-dev
    - postgresql=9.5*
    - python-psycopg2
    - unzip


- name: ensure the PostgreSQL service is running
  service: name=postgresql state=started  enabled=yes


- name: copy configuration file
  copy: >
    src=postgresql.conf dest=/etc/postgresql/9.5/main/postgresql.conf
    owner=postgres group=postgres mode=0644
  become: True
  notify: restart postgres


- name: copy client authentication configuration file
  copy: >
    src=pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf
    owner=postgres group=postgres mode=0640
  become: True
  notify: restart postgres


- name: create database user
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ db_pass }}"
  become: True
  become_user: postgres


- name: copy postgress credentials
  template: src=.pgpass.j2 dest={{ hostvars[inventory_hostname].ansible_user_dir }}/.pgpass mode=600


- name: download sample database
  unarchive:
    src: "http://www.sportsdb.org/modules/sd/assets/downloads/sportsdb_sample_postgresql.zip"
    copy: no
    dest: /tmp
    list_files: yes
  register: database_dump


- name: create the database
  postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"
    encoding: UTF8
    lc_ctype: "{{ locale }}"
    lc_collate: "{{ locale }}"
    template: template0
  become: True
  become_user: postgres
  notify: load database
