---
# - name: Deploy a postgress DB
#   hosts:
#     - all
#   user: ubuntu
#   become: true
#   gather_facts: false
#   pre_tasks:
#     - name: wait for ssh server to be running
#       become: false
#       local_action: wait_for port=22 host="{{ item }}" search_regex=OpenSSH
#       with_items: '{{ groups.ec2 }}'
#     - name: Install python2
#       raw: "apt-get -qq update && apt-get -yq install python python-simplejson"
#     - name: Gather facts
#       setup:
#
#   roles:
#     - common

- hosts: ec2
  gather_facts: false
  tasks:
    - name: Wait for ssh
      local_action: wait_for port=22 host="{{ item }}" search_regex=OpenSSH
      with_items: '{{ groups.ec2 }}'

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install python2
      raw: "apt-get -qq update && apt-get -yq install python python-simplejson"

- hosts: db
  roles:
    - common
