---
- hosts: ec2
  gather_facts: false
  tasks:
    - name: Wait for ssh
      local_action: wait_for port=22 host="{{ item }}" search_regex=OpenSSH
      with_items: '{{ groups.ec2 }}'

- hosts: all
  gather_facts: false
  become: True
  tasks:
    - name: Install python2
      raw: "apt-get -qq update && apt-get -yq install python python-simplejson"

- hosts: db
  vars_files:
    - secrets.yml
  roles:
    - common
    - role: postgres
      database_name: "{{ proj_name }}"
      database_user: "{{ proj_name }}"
